version: '3.8'

services:
  app:
    build: .
    container_name: sistema-pedidos
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - pedido-network

  # Kafka services for development
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - pedido-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pedido-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - pedido-network

# Se no futuro a aplicação precisar de um banco de dados, pode adicionar:
# db:
#   image: postgres:14-alpine
#   container_name: pedido-db
#   ports:
#     - "5432:5432"
#   environment:
#     - POSTGRES_DB=pedidodb
#     - POSTGRES_USER=pedidouser
#     - POSTGRES_PASSWORD=pedidopass
#   volumes:
#     - pedido-db-data:/var/lib/postgresql/data
#   networks:
#     - pedido-network

networks:
  pedido-network:
    driver: bridge

# volumes:
#   pedido-db-data:
